"""
convert_trades.py
─────────────────────────────────────────────────────────────
Called by update_dashboard.bat.
1. Reads the master CSV and writes a per-day JS file for each date.
2. Scans ALL existing per-day files and merges them into trades.js.

This means the dashboard always shows the full history even if
the Windows bot log only has today's trades — past days' files
already exist in the data folder from previous runs.

Usage: python convert_trades.py <src_csv> <dest_js>
"""

import csv, json, os, re, sys
from datetime import datetime

if len(sys.argv) < 3:
    print("[ERROR] Usage: python convert_trades.py <src_csv> <dest_js>")
    sys.exit(1)

src      = sys.argv[1]
dst      = sys.argv[2]
data_dir = os.path.dirname(dst)

# ── Read source CSV ───────────────────────────────────────────
with open(src, newline='', encoding='utf-8') as f:
    rows = [{k.strip(): v.strip() for k, v in row.items()} for row in csv.DictReader(f)]

# ── Group by date and write per-day JS files ─────────────────
by_day = {}
for row in rows:
    day = row.get('exit_time', '')[:10]
    if day:
        by_day.setdefault(day, []).append(row)

for day, trades in by_day.items():
    path = os.path.join(data_dir, f"trades_{day}.js")
    with open(path, 'w', encoding='utf-8') as f:
        f.write(f'// Auto-generated by update_dashboard.bat — {day}\n')
        f.write('// Do not edit manually\n\n')
        f.write('window.TRADES_DAYS = window.TRADES_DAYS || {};\n')
        f.write(f'window.TRADES_DAYS["{day}"] = ')
        f.write(json.dumps(trades, indent=2))
        f.write(';\n')
    print(f"[OK] Wrote {len(trades)} trades -> trades_{day}.js")

# ── Merge ALL existing day files into trades.js ──────────────
day_files = sorted([
    fi for fi in os.listdir(data_dir)
    if re.match(r'^trades_\d{4}-\d{2}-\d{2}\.js$', fi)
])

all_trades = []
for fname in day_files:
    with open(os.path.join(data_dir, fname), encoding='utf-8') as f:
        content = f.read()
    match = re.search(r'window\.TRADES_DAYS\[".+?"\]\s*=\s*(\[.*?\]);', content, re.DOTALL)
    if match:
        all_trades.extend(json.loads(match.group(1)))

all_trades.sort(key=lambda t: t.get('exit_time', ''))
now  = datetime.now().strftime('%Y-%m-%d %H:%M:%S')
days = sorted(set(t.get('exit_time', '')[:10] for t in all_trades if t.get('exit_time')))

with open(dst, 'w', encoding='utf-8') as f:
    f.write('// Auto-generated by update_dashboard.bat\n')
    f.write(f'// Merged from {len(day_files)} daily files - {len(days)} trading days\n')
    f.write('// Do not edit manually\n\n')
    f.write('window.TRADES_DATA = ')
    f.write(json.dumps(all_trades, indent=2))
    f.write(';\n\n')
    f.write(f'window.LAST_UPDATED = "{now}";\n')

print(f"[OK] Merged {len(all_trades)} trades from {len(day_files)} day files -> trades.js")
print(f"     Days: {', '.join(days)}")
