#!/bin/bash
# ─────────────────────────────────────────────────────────────
# update_dashboard.sh
# Copies the bot trade log to the dashboard, converts it to
# a JavaScript data file, then pushes to GitHub Pages.
#
# Schedule: runs automatically via launchd at 23:00 Turkey time
# Run manually anytime: bash ~/mnq-bot/scripts/update_dashboard.sh
# ─────────────────────────────────────────────────────────────

SOURCE="$HOME/mnq-bot/logs/mnq_trades_log.csv"
DASHBOARD_DIR="$HOME/mnq-bot/dashboard"
DEST_DATA_DIR="$DASHBOARD_DIR/data"
DEST_CSV="$DEST_DATA_DIR/mnq_trades.csv"
DEST_JS="$DEST_DATA_DIR/trades.js"
LOG="$HOME/mnq-bot/logs/dashboard_update.log"

# ── Ensure output directory exists ──────────────────────────
mkdir -p "$DEST_DATA_DIR"

echo "──────────────────────────────────────────" >> "$LOG"
echo "[$(date '+%Y-%m-%d %H:%M:%S')] Dashboard update started" >> "$LOG"

# ── Check source file exists ─────────────────────────────────
if [ ! -f "$SOURCE" ]; then
    echo "[ERROR] Source not found: $SOURCE" | tee -a "$LOG"
    exit 1
fi

# ── Copy the raw CSV ─────────────────────────────────────────
cp "$SOURCE" "$DEST_CSV"
echo "[OK] Copied CSV to $DEST_CSV" >> "$LOG"

# ── Convert CSV to JavaScript data file ──────────────────────
python3 - "$DEST_CSV" "$DEST_JS" << 'PYEOF'
import csv
import json
import sys
from datetime import datetime

src = sys.argv[1]
dst = sys.argv[2]

with open(src, newline='', encoding='utf-8') as f:
    reader = csv.DictReader(f)
    rows = list(reader)

clean = []
for row in rows:
    clean.append({k.strip(): v.strip() for k, v in row.items()})

now = datetime.now().strftime('%Y-%m-%d %H:%M:%S')

with open(dst, 'w', encoding='utf-8') as f:
    f.write('// Auto-generated by update_dashboard.sh\n')
    f.write('// Do not edit manually\n\n')
    f.write('window.TRADES_DATA = ')
    f.write(json.dumps(clean, indent=2))
    f.write(';\n\n')
    f.write(f'window.LAST_UPDATED = "{now}";\n')

print(f"[OK] Wrote {len(clean)} trades to {dst}")
PYEOF

if [ $? -ne 0 ]; then
    echo "[ERROR] Python conversion failed" | tee -a "$LOG"
    exit 1
fi

echo "[OK] trades.js generated successfully" >> "$LOG"

# ── Push to GitHub Pages ─────────────────────────────────────
cd "$DASHBOARD_DIR"

git add data/trades.js data/mnq_trades.csv
git commit -m "Dashboard update $(date '+%Y-%m-%d %H:%M')"
git push

if [ $? -eq 0 ]; then
    echo "[OK] Pushed to GitHub Pages" >> "$LOG"
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] Dashboard update complete" >> "$LOG"
    echo "Dashboard updated and published successfully"
    echo "View at: https://cozerdag.github.io/mnq-dashboard"
else
    echo "[ERROR] Git push failed" | tee -a "$LOG"
    exit 1
fi
