#!/bin/bash
# ─────────────────────────────────────────────────────────────
# update_dashboard.sh
# Copies the bot trade log to the dashboard and converts it
# to a JavaScript data file so the HTML can load it locally.
#
# Schedule: runs automatically via launchd at 23:00 Turkey time
# Run manually anytime: bash ~/mnq-bot/scripts/update_dashboard.sh
# ─────────────────────────────────────────────────────────────

SOURCE="$HOME/mnq-bot/logs/mnq_trades_log.csv"
DASHBOARD_DIR="$HOME/mnq-bot/dashboard"
DEST_DATA_DIR="$DASHBOARD_DIR/data"
DEST_CSV="$DEST_DATA_DIR/mnq_trades.csv"
DEST_JS="$DEST_DATA_DIR/trades.js"
LOG="$HOME/mnq-bot/logs/dashboard_update.log"

# ── Ensure output directory exists ──────────────────────────
mkdir -p "$DEST_DATA_DIR"

echo "──────────────────────────────────────────" >> "$LOG"
echo "[$(date '+%Y-%m-%d %H:%M:%S')] Dashboard update started" >> "$LOG"

# ── Check source file exists ─────────────────────────────────
if [ ! -f "$SOURCE" ]; then
    echo "[ERROR] Source not found: $SOURCE" | tee -a "$LOG"
    exit 1
fi

# ── Copy the raw CSV ─────────────────────────────────────────
cp "$SOURCE" "$DEST_CSV"
echo "[OK] Copied CSV to $DEST_CSV" >> "$LOG"

# ── Convert CSV to JavaScript data file ──────────────────────
# Uses Python3 (available on all Macs) to parse CSV → JSON
python3 - "$DEST_CSV" "$DEST_JS" << 'PYEOF'
import csv
import json
import sys
from datetime import datetime

src = sys.argv[1]
dst = sys.argv[2]

with open(src, newline='', encoding='utf-8') as f:
    reader = csv.DictReader(f)
    rows = list(reader)

# Clean up any whitespace in keys/values
clean = []
for row in rows:
    clean.append({k.strip(): v.strip() for k, v in row.items()})

now = datetime.now().strftime('%Y-%m-%d %H:%M:%S')

with open(dst, 'w', encoding='utf-8') as f:
    f.write('// Auto-generated by update_dashboard.sh\n')
    f.write('// Do not edit manually\n\n')
    f.write('window.TRADES_DATA = ')
    f.write(json.dumps(clean, indent=2))
    f.write(';\n\n')
    f.write(f'window.LAST_UPDATED = "{now}";\n')

print(f"[OK] Wrote {len(clean)} trades to {dst}")
PYEOF

if [ $? -eq 0 ]; then
    echo "[OK] trades.js generated successfully" >> "$LOG"
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] Dashboard update complete" >> "$LOG"
    echo "✅ Dashboard updated — $(python3 -c "import csv; r=list(csv.DictReader(open('$SOURCE'))); print(len(r),'trades')" 2>/dev/null || echo 'see logs')"
    echo "   Open: $DASHBOARD_DIR/index.html"
else
    echo "[ERROR] Python conversion failed" | tee -a "$LOG"
    exit 1
fi
